# Generated by Django 5.1.15 on 2026-05-13 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("prompt", models.TextField()),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "focus_area",
                    models.CharField(
                        choices=[
                            ("FULL_BODY", "Full Body"),
                            ("CORE", "Core"),
                            ("LOWER_BODY", "Lower Body"),
                            ("UPPER_BODY", "Upper Body"),
                            ("FLEXIBILITY", "Flexibility"),
                            ("BALANCE", "Balance"),
                            ("BACK_HEALTH", "Back Health"),
                        ],
                        default="FULL_BODY",
                        max_length=24,
                    ),
                ),
                ("difficulty", models.CharField(default="BEGINNER", max_length=16)),
                (
                    "music_style",
                    models.CharField(default="Calm Ambient", max_length=60),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCRIPTING", "Scripting"),
                            ("SCRIPT_READY", "Script Ready"),
                            ("VOICING", "Generating Voice"),
                            ("AVATAR_RENDERING", "Generating Avatar"),
                            ("RENDERING", "Rendering Video"),
                            ("RENDERED", "Rendered"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("script_json", models.JSONField(default=dict)),
                ("voice_url", models.URLField(blank=True, default="")),
                ("avatar_url", models.URLField(blank=True, default="")),
                ("video_url", models.URLField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitness_classes",
                        to="studios.studio",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("SCRIPT", "Script Generation"),
                            ("VOICE", "Voice Generation"),
                            ("AVATAR", "Avatar Rendering"),
                            ("RENDER", "Final Video Render"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fitness_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="classes.fitnessclass",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
