# Generated by Django 5.1.15 on 2026-05-13 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("brand_color", models.CharField(default="#264D3B", max_length=16)),
                (
                    "voice_preference",
                    models.CharField(default="warm_female", max_length=64),
                ),
                (
                    "avatar_preference",
                    models.CharField(default="instructor_neutral", max_length=64),
                ),
                ("tagline", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
