# Generated by Django 5.1.15 on 2026-05-13 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MAT_PILATES", "Mat Pilates"),
                            ("REFORMER", "Reformer"),
                            ("CORE", "Core"),
                            ("FLEXIBILITY", "Flexibility"),
                            ("BALANCE", "Balance"),
                            ("STRENGTH", "Strength"),
                            ("CARDIO", "Cardio"),
                            ("WARMUP", "Warm-up"),
                            ("COOLDOWN", "Cool-down"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                        ],
                        default="BEGINNER",
                        max_length=16,
                    ),
                ),
                ("muscle_groups", models.JSONField(default=list)),
                ("instructions", models.TextField()),
                ("safety_notes", models.TextField(blank=True, default="")),
                ("demo_video_url", models.URLField(blank=True, default="")),
                ("demo_thumbnail_url", models.URLField(blank=True, default="")),
                ("duration_seconds", models.PositiveIntegerField(default=45)),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alternatives",
                    models.ManyToManyField(blank=True, to="exercises.exercise"),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="studios.studio",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
